sudo: required
services:
  - docker

before_install:
  - docker build -t weenta/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run -e CI=true weenta/react-test npm run test

after_success:
  - docker build -t weenta/multi-client ./client
  - docker build -t weenta/multi-nginx ./nginx
  - docker build -t weenta/multi-server ./server
  - docker build -t weenta/multi-worker ./worker
  # login to docker CLI 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push weenta/multi-client
  - docker push weenta/multi-nginx
  - docker push weenta/multi-server
  - docker push weenta/multi-worker